security:
  basic:
    enabled: true
  user:
    name: user
    password: password123456
server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tangmin721/s2f-cloud
          username:
          password:
          search-paths: s2f-cloud-config-server/config-git-path
          clone-on-start: true
  application:
    name: s2f-cloud-config-server

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: BEIJING      # eureka可以理解的元数据