profile: profile-default-git-path-master1.0

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123456@localhost:8761/eureka
  instance:
    #statusPageUrlPath: ${server.context-path}/info
    #healthCheckUrlPath: ${server.context-path}/health
    leaseRenewalIntervalInSeconds: 1  # 注册服务默认心跳时间为30秒，当一个服务器不可用，需要3个心跳才能让服务器和客户端的元数据相同。可以使用eureka.instance.leaseRenewalIntervalInSeconds加快这个过程。在生产环境最好使用默认配置。
    leaseExpirationDurationInSeconds: 2 #LeaseExpirationDurationInSeconds (默认90秒)即Server注册中心端默认多少秒没有收到client端心跳就认为client失效了，失效后会将对应client从注册中心移除。
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: BEIJING      # eureka可以理解的元数据

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/apple?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

myprofile: config-localapplication-refresh